/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyProject;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.text.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Md. Younus Hosssain Ahsan
 */

public class Book_Info extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    
    Timer timer;
    SimpleDateFormat rdf = new SimpleDateFormat("HH");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        
    public Book_Info() {
        
        initComponents();
        
        timer = new Timer(1000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                               
                Date CurrentDate = new Date();
                int check = Integer.parseInt(rdf.format(CurrentDate));
                if(check > 11)
                    Date.setText(sdf.format(CurrentDate) + " PM");
                else
                    Date.setText(sdf.format(CurrentDate) + " AM");
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_a_Student = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        Department = new javax.swing.JButton();
        Student_Info = new javax.swing.JButton();
        Category = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Menu_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add_a_Student.setBackground(new java.awt.Color(253, 229, 210));
        Add_a_Student.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add_a_Student.setText("New Book");
        Add_a_Student.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Add_a_Student.setContentAreaFilled(false);
        Add_a_Student.setOpaque(true);
        Add_a_Student.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Add_a_StudentMouseMoved(evt);
            }
        });
        Add_a_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_a_StudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_a_StudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_a_StudentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Add_a_StudentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Add_a_StudentMouseReleased(evt);
            }
        });
        Add_a_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_a_StudentActionPerformed(evt);
            }
        });
        getContentPane().add(Add_a_Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, 45));

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(253, 229, 210));
        Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setBorder(null);
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
        });
        Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateMouseClicked(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 180, -1));

        Department.setBackground(new java.awt.Color(253, 229, 210));
        Department.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Department.setText("Department");
        Department.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Department.setContentAreaFilled(false);
        Department.setOpaque(true);
        Department.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DepartmentMouseMoved(evt);
            }
        });
        Department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepartmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepartmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepartmentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DepartmentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DepartmentMouseReleased(evt);
            }
        });
        Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentActionPerformed(evt);
            }
        });
        getContentPane().add(Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 200, 45));

        Student_Info.setBackground(new java.awt.Color(253, 229, 210));
        Student_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Student_Info.setText("Book List");
        Student_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Student_Info.setContentAreaFilled(false);
        Student_Info.setOpaque(true);
        Student_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Student_InfoMouseMoved(evt);
            }
        });
        Student_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Student_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Student_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Student_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Student_InfoMouseReleased(evt);
            }
        });
        Student_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Student_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 200, 45));

        Category.setBackground(new java.awt.Color(253, 229, 210));
        Category.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Category.setText("Category");
        Category.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Category.setContentAreaFilled(false);
        Category.setOpaque(true);
        Category.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CategoryMouseMoved(evt);
            }
        });
        Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CategoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CategoryMouseReleased(evt);
            }
        });
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        getContentPane().add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 45));

        Back.setBackground(new java.awt.Color(253, 229, 210));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Back.setContentAreaFilled(false);
        Back.setOpaque(true);
        Back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackMouseMoved(evt);
            }
        });
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 200, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 170));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/book icon.gif"))); // NOI18N
        jLabel4.setText(" Book Information ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 110));

        Menu_icon.setBackground(new java.awt.Color(255, 255, 255));
        Menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/bg.png"))); // NOI18N
        getContentPane().add(Menu_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepartmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseMoved
        Department.setCursor(SignIN.cursor);
    }//GEN-LAST:event_DepartmentMouseMoved

    private void DepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseClicked
        Department.setBackground(new Color(255,255,0).brighter());
        Department.setForeground(Color.WHITE);
    }//GEN-LAST:event_DepartmentMouseClicked

    private void DepartmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseEntered
        Department.setBackground(new Color(253,229,196).brighter());
        Department.setForeground(Color.BLACK);
    }//GEN-LAST:event_DepartmentMouseEntered

    private void DepartmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseExited
        Department.setBackground(new Color(253,229,210));
        Department.setForeground(Color.BLACK);
    }//GEN-LAST:event_DepartmentMouseExited

    private void DepartmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMousePressed
        Department.setBackground(new Color(255,255,100).brighter());
        Department.setForeground(Color.BLACK);
    }//GEN-LAST:event_DepartmentMousePressed

    private void DepartmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseReleased
        Department.setBackground(new Color(253,229,210));
        Department.setForeground(Color.BLACK);
    }//GEN-LAST:event_DepartmentMouseReleased

    private void DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentActionPerformed
        new Departments().setVisible(true);
    }//GEN-LAST:event_DepartmentActionPerformed

    private void Student_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseMoved
        Student_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Student_InfoMouseMoved

    private void Student_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseClicked
        Student_Info.setBackground(new Color(255,255,0).brighter());
        Student_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Student_InfoMouseClicked

    private void Student_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseEntered
        Student_Info.setBackground(new Color(253,229,196).brighter());
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMouseEntered

    private void Student_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseExited
        Student_Info.setBackground(new Color(253,229,210));
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMouseExited

    private void Student_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMousePressed
        Student_Info.setBackground(new Color(255,255,100).brighter());
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMousePressed

    private void Student_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseReleased
        Student_Info.setBackground(new Color(253,229,210));
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMouseReleased

    private void Student_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_InfoActionPerformed
        try {
            new Book_List().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Book_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Student_InfoActionPerformed

    private void CategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseMoved
        Category.setCursor(SignIN.cursor);
    }//GEN-LAST:event_CategoryMouseMoved

    private void CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseClicked
        Category.setBackground(new Color(255,255,0).brighter());
        Category.setForeground(Color.WHITE);
    }//GEN-LAST:event_CategoryMouseClicked

    private void CategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseEntered
        Category.setBackground(new Color(253,229,196).brighter());
        Category.setForeground(Color.BLACK);
    }//GEN-LAST:event_CategoryMouseEntered

    private void CategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseExited
        Category.setBackground(new Color(253,229,210));
        Category.setForeground(Color.BLACK);
    }//GEN-LAST:event_CategoryMouseExited

    private void CategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMousePressed
        Category.setBackground(new Color(255,255,100).brighter());
        Category.setForeground(Color.BLACK);
    }//GEN-LAST:event_CategoryMousePressed

    private void CategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseReleased
        Category.setBackground(new Color(253,229,210));
        Category.setForeground(Color.BLACK);
    }//GEN-LAST:event_CategoryMouseReleased

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        new Categories().setVisible(true);
    }//GEN-LAST:event_CategoryActionPerformed

    private void BackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseMoved
        Back.setCursor(SignIN.cursor);
    }//GEN-LAST:event_BackMouseMoved

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        Back.setBackground(new Color(255,255,0).brighter());
        Back.setForeground(Color.WHITE);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setBackground(new Color(253,229,196).brighter());
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(new Color(253,229,210));
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseExited

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        Back.setBackground(new Color(255,255,100).brighter());
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMousePressed

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
        Back.setBackground(new Color(253,229,210));
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseReleased

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();   
    }//GEN-LAST:event_BackActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFocusGained

    private void DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateMouseClicked

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void Add_a_StudentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_a_StudentMouseMoved
        Add_a_Student.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Add_a_StudentMouseMoved

    private void Add_a_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_a_StudentMouseClicked
        Add_a_Student.setBackground(new Color(255,255,0).brighter());
        Add_a_Student.setForeground(Color.WHITE);
    }//GEN-LAST:event_Add_a_StudentMouseClicked

    private void Add_a_StudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_a_StudentMouseEntered
        Add_a_Student.setBackground(new Color(253,229,196).brighter());
        Add_a_Student.setForeground(Color.BLACK);
    }//GEN-LAST:event_Add_a_StudentMouseEntered

    private void Add_a_StudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_a_StudentMouseExited
        Add_a_Student.setBackground(new Color(253,229,210));
        Add_a_Student.setForeground(Color.BLACK);
    }//GEN-LAST:event_Add_a_StudentMouseExited

    private void Add_a_StudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_a_StudentMousePressed
        Add_a_Student.setBackground(new Color(255,255,100).brighter());
        Add_a_Student.setForeground(Color.BLACK);
    }//GEN-LAST:event_Add_a_StudentMousePressed

    private void Add_a_StudentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_a_StudentMouseReleased
        Add_a_Student.setBackground(new Color(253,229,210));
        Add_a_Student.setForeground(Color.BLACK);
    }//GEN-LAST:event_Add_a_StudentMouseReleased

    private void Add_a_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_a_StudentActionPerformed
        try {
            new New_Book().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Book_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Add_a_StudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_a_Student;
    private javax.swing.JButton Back;
    private javax.swing.JButton Category;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Department;
    private javax.swing.JLabel Menu_icon;
    private javax.swing.JButton Student_Info;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
