/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyProject;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.text.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Md. Younus Hosssain Ahsan
 */

public class Menu extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    
    Timer timer;
    SimpleDateFormat rdf = new SimpleDateFormat("HH");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        
    public Menu() {
        
        initComponents();
        
        timer = new Timer(1000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                               
                Date CurrentDate = new Date();
                int check = Integer.parseInt(rdf.format(CurrentDate));
                if(check > 11)
                    Date.setText(sdf.format(CurrentDate) + " PM");
                else
                    Date.setText(sdf.format(CurrentDate) + " AM");
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        New_Borrow = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        Book_Info = new javax.swing.JButton();
        Student_Info = new javax.swing.JButton();
        Borrow_List = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        User_Info = new javax.swing.JButton();
        Menu_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        New_Borrow.setBackground(new java.awt.Color(253, 229, 210));
        New_Borrow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        New_Borrow.setText("New Borrow");
        New_Borrow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        New_Borrow.setContentAreaFilled(false);
        New_Borrow.setOpaque(true);
        New_Borrow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                New_BorrowMouseMoved(evt);
            }
        });
        New_Borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_BorrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                New_BorrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                New_BorrowMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                New_BorrowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                New_BorrowMouseReleased(evt);
            }
        });
        New_Borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_BorrowActionPerformed(evt);
            }
        });
        getContentPane().add(New_Borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, 45));

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(253, 229, 210));
        Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setBorder(null);
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
        });
        Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateMouseClicked(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 180, -1));

        Book_Info.setBackground(new java.awt.Color(253, 229, 210));
        Book_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Book_Info.setText("Book Info");
        Book_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Book_Info.setContentAreaFilled(false);
        Book_Info.setOpaque(true);
        Book_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Book_InfoMouseMoved(evt);
            }
        });
        Book_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Book_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Book_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Book_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Book_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Book_InfoMouseReleased(evt);
            }
        });
        Book_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Book_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 45));

        Student_Info.setBackground(new java.awt.Color(253, 229, 210));
        Student_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Student_Info.setText("Student Info");
        Student_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Student_Info.setContentAreaFilled(false);
        Student_Info.setOpaque(true);
        Student_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Student_InfoMouseMoved(evt);
            }
        });
        Student_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Student_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Student_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Student_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Student_InfoMouseReleased(evt);
            }
        });
        Student_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Student_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 200, 45));

        Borrow_List.setBackground(new java.awt.Color(253, 229, 210));
        Borrow_List.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Borrow_List.setText("Borrow List");
        Borrow_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Borrow_List.setContentAreaFilled(false);
        Borrow_List.setOpaque(true);
        Borrow_List.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Borrow_ListMouseMoved(evt);
            }
        });
        Borrow_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Borrow_ListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Borrow_ListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Borrow_ListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Borrow_ListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Borrow_ListMouseReleased(evt);
            }
        });
        Borrow_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrow_ListActionPerformed(evt);
            }
        });
        getContentPane().add(Borrow_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 200, 45));

        Exit.setBackground(new java.awt.Color(253, 229, 210));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        Exit.setContentAreaFilled(false);
        Exit.setOpaque(true);
        Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ExitMouseMoved(evt);
            }
        });
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 200, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 170));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/book icon.gif"))); // NOI18N
        jLabel4.setText(" Library Maintenance System ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 110));

        User_Info.setBackground(new java.awt.Color(253, 229, 210));
        User_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        User_Info.setText("Personal Info");
        User_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        User_Info.setContentAreaFilled(false);
        User_Info.setOpaque(true);
        User_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                User_InfoMouseMoved(evt);
            }
        });
        User_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                User_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                User_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                User_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                User_InfoMouseReleased(evt);
            }
        });
        User_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(User_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 200, 45));

        Menu_icon.setBackground(new java.awt.Color(255, 255, 255));
        Menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/bg.png"))); // NOI18N
        getContentPane().add(Menu_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Book_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_InfoMouseMoved
        Book_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Book_InfoMouseMoved

    private void Book_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_InfoMouseClicked
        Book_Info.setBackground(new Color(255,255,0).brighter());
        Book_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Book_InfoMouseClicked

    private void Book_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_InfoMouseEntered
        Book_Info.setBackground(new Color(253,229,196).brighter());
        Book_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Book_InfoMouseEntered

    private void Book_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_InfoMouseExited
        Book_Info.setBackground(new Color(253,229,210));
        Book_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Book_InfoMouseExited

    private void Book_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_InfoMousePressed
        Book_Info.setBackground(new Color(255,255,100).brighter());
        Book_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Book_InfoMousePressed

    private void Book_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Book_InfoMouseReleased
        Book_Info.setBackground(new Color(253,229,210));
        Book_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Book_InfoMouseReleased

    private void Book_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_InfoActionPerformed
        new Book_Info().setVisible(true);
    }//GEN-LAST:event_Book_InfoActionPerformed

    private void Student_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseMoved
        Student_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Student_InfoMouseMoved

    private void Student_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseClicked
        Student_Info.setBackground(new Color(255,255,0).brighter());
        Student_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Student_InfoMouseClicked

    private void Student_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseEntered
        Student_Info.setBackground(new Color(253,229,196).brighter());
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMouseEntered

    private void Student_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseExited
        Student_Info.setBackground(new Color(253,229,210));
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMouseExited

    private void Student_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMousePressed
        Student_Info.setBackground(new Color(255,255,100).brighter());
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMousePressed

    private void Student_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_InfoMouseReleased
        Student_Info.setBackground(new Color(253,229,210));
        Student_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Student_InfoMouseReleased

    private void Student_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_InfoActionPerformed
        try {
            new Student_Info().setVisible(true);
        } catch (ClassNotFoundException ex) {}
    }//GEN-LAST:event_Student_InfoActionPerformed

    private void Borrow_ListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow_ListMouseMoved
        Borrow_List.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Borrow_ListMouseMoved

    private void Borrow_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow_ListMouseClicked
        Borrow_List.setBackground(new Color(255,255,0).brighter());
        Borrow_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Borrow_ListMouseClicked

    private void Borrow_ListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow_ListMouseEntered
        Borrow_List.setBackground(new Color(253,229,196).brighter());
        Borrow_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Borrow_ListMouseEntered

    private void Borrow_ListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow_ListMouseExited
        Borrow_List.setBackground(new Color(253,229,210));
        Borrow_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Borrow_ListMouseExited

    private void Borrow_ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow_ListMousePressed
        Borrow_List.setBackground(new Color(255,255,100).brighter());
        Borrow_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Borrow_ListMousePressed

    private void Borrow_ListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrow_ListMouseReleased
        Borrow_List.setBackground(new Color(253,229,210));
        Borrow_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Borrow_ListMouseReleased

    private void Borrow_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrow_ListActionPerformed
        new Pending_Borrow_List().setVisible(true);
    }//GEN-LAST:event_Borrow_ListActionPerformed

    private void ExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseMoved
        Exit.setCursor(SignIN.cursor);
    }//GEN-LAST:event_ExitMouseMoved

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Exit.setBackground(new Color(255,255,0).brighter());
        Exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setBackground(new Color(253,229,196).brighter());
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setBackground(new Color(253,229,210));
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        Exit.setBackground(new Color(255,255,100).brighter());
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMousePressed

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
        Exit.setBackground(new Color(253,229,210));
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMouseReleased

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int result = JOptionPane.showConfirmDialog(this,"Do you want to close ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                
        if(result == JOptionPane.YES_OPTION){
           
              System.exit(0);              
        }   
    }//GEN-LAST:event_ExitActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFocusGained

    private void DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateMouseClicked

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void New_BorrowMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BorrowMouseMoved
        New_Borrow.setCursor(SignIN.cursor);
    }//GEN-LAST:event_New_BorrowMouseMoved

    private void New_BorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BorrowMouseClicked
        New_Borrow.setBackground(new Color(255,255,0).brighter());
        New_Borrow.setForeground(Color.WHITE);
    }//GEN-LAST:event_New_BorrowMouseClicked

    private void New_BorrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BorrowMouseEntered
        New_Borrow.setBackground(new Color(253,229,196).brighter());
        New_Borrow.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_BorrowMouseEntered

    private void New_BorrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BorrowMouseExited
        New_Borrow.setBackground(new Color(253,229,210));
        New_Borrow.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_BorrowMouseExited

    private void New_BorrowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BorrowMousePressed
        New_Borrow.setBackground(new Color(255,255,100).brighter());
        New_Borrow.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_BorrowMousePressed

    private void New_BorrowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BorrowMouseReleased
        New_Borrow.setBackground(new Color(253,229,210));
        New_Borrow.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_BorrowMouseReleased

    private void New_BorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_BorrowActionPerformed
        try {
            new Borrowing_Book().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_New_BorrowActionPerformed

    private void User_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_InfoMouseMoved
        User_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_User_InfoMouseMoved

    private void User_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_InfoMouseClicked
        User_Info.setBackground(new Color(255,255,0).brighter());
        User_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_User_InfoMouseClicked

    private void User_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_InfoMouseEntered
        User_Info.setBackground(new Color(253,229,196).brighter());
        User_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_User_InfoMouseEntered

    private void User_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_InfoMouseExited
        User_Info.setBackground(new Color(253,229,210));
        User_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_User_InfoMouseExited

    private void User_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_InfoMousePressed
        User_Info.setBackground(new Color(255,255,100).brighter());
        User_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_User_InfoMousePressed

    private void User_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_InfoMouseReleased
        User_Info.setBackground(new Color(253,229,210));
        User_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_User_InfoMouseReleased

    private void User_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_InfoActionPerformed
        try {
            new User_Info().setVisible(true);
        } catch (ClassNotFoundException ex) {}
    }//GEN-LAST:event_User_InfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book_Info;
    private javax.swing.JButton Borrow_List;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Menu_icon;
    private javax.swing.JButton New_Borrow;
    private javax.swing.JButton Student_Info;
    private javax.swing.JButton User_Info;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
